### ISSUE TITLE
Can't install BayHunter

### ISSUE THREAD

**Issue by yjlimm** [jenndrei/BayHunter#17]
To install BayHunter, I installed packages in my conda environment
• python==3.8.5
• matplotlib==3.7.3
• numpy==1.24.4
• pyPdf=4.3.1
• configobj=5.0.8
• zmq=0.0.0 (installed by "pip install zmq")
(pyzaq==26.1.0 also installed)
• Cython==3.0.11

and type "python setup.py install" or "sudo python setup.py install".
but,  I can't install BayHunter...

When  I type "from BayHunter import utils",
#####################################
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'BayHunter'
#####################################
is returned.

I want to install this program..

**Comment by kuanyuke** [comment]
Did you get an error message during installation? If so, could you provide me with the error message?
It seems that the package may not have been installed correctly in your conda environment's site-packages. I re-downloaded the package and set up a new conda environment similar to yours on different machines without encountering any issues. You can try running pip install --upgrade setuptools before executing python setup.py install to ensure that setuptools is up to date and see if that resolves the issue.

**Comment by yjlimm** [comment]
I install successfully! maybe, numpy has problem..
Thank you!!
