### ISSUE TITLE
numpy import fail

### ISSUE THREAD

**Issue by ajay6763** [jenndrei/BayHunter#3]
Hello, Jennifer
Thanks for this great tool. I was trying is on Ubuntu 64 bit machine in python2.7 environment and got the following error related to the numpy.
" ImportError: numpy.core.multiarray failed to import "

Could you please share the requirement file with versions of the python libs you are using.

Thanks 
ajay

**Comment by jenndrei** [comment]
Hi Ajay,
Which numpy version are you using? Have you tried to update numpy?
I found this: https://github.com/tensorflow/tensorflow/issues/559

**Comment by ajay6763** [comment]
Thanks, Jennifer
It is working now. 
I have numpy==1.17.4

**Comment by jenndrei** [comment]
Great!
